<?php
/**
 * Created by PhpStorm.
 * User: shellvon
 * Date: 16/6/14
 * Time: 下午4:42.
 */

namespace Model;

use MicroMan\MicroModel;

class LogModel extends MicroModel
{
    const TABLE_NAME = 'operation_logs';

    /**
     * @return static
     */
    public static function getInstance()
    {
        return parent::createInstance(__CLASS__); // TODO: Change the autogenerated stub
    }

    public function getTableName()
    {
        return self::TABLE_NAME; // TODO: Change the autogenerated stub
    }

    /**
     * 增加一个日志.
     *
     * @param $action
     * @param $operator_id
     * @param null $new_data
     * @param null $old_data
     *
     * @return false|int
     */
    public function addLogs($action, $operator_id, $new_data = null, $old_data = null)
    {
        return $this->insert(
            array(
                'create_time' => time(),
                'action' => $action,
                'operator_id' => $operator_id,
                'old_data' => $old_data == null ? null : json_encode($old_data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT),
                'new_data' => $new_data == null ? null : json_encode($new_data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT),
            )
        );
    }
}
