<?php
/**
 * Created by PhpStorm.
 * User: shellvon
 * Date: 16/4/16
 * Time: 下午5:19.
 */

namespace Model;

use MicroMan\MicroModel;

class RecordModel extends MicroModel
{
    const TABLE_NAME = 'cost_records';

    /**
     * @return static
     */
    public static function getInstance()
    {
        return parent::createInstance(__CLASS__); // TODO: Change the autogenerated stub
    }

    public function getTableName()
    {
        return self::TABLE_NAME; // TODO: Change the autogenerated stub
    }

    public function query($sql)
    {
        return $this->db_engine->query($sql);
    }
}
