<?php
/**
 * Created by PhpStorm.
 * User: shellvon
 * Date: 16/4/17
 * Time: 下午11:46.
 */

namespace Controller;

use MicroMan\MicroController;
use Model\UserModel;
use Model\CostTypeModel;

class BaseController extends MicroController
{
    private $no_login_action_lst = array('login', 'register');

    protected $user_info = null;
    protected $user_lst = null;
    protected $type_map = null;
    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
        $user_obj = UserModel::getInstance();
        $cost_type_obj = CostTypeModel::getInstance();

        //现有用户列表.
        $this->user_lst = $user_obj->getAll(null, 'id, nickname', 'id');
        //现有的类型列表.
        $this->type_map = $cost_type_obj->getAll(null, 'id, who, description', 'id');
        $this->tpl_engine->assign(
            array(
                'user_lst' => $this->user_lst,
                'type_map' => $this->type_map,
            )
        );
        $action_name_lower = strtolower($this->action_name);
        if (in_array($action_name_lower, $this->no_login_action_lst)) {
            return;
        }
        if (!isset($_SESSION['uid'])) {
            $_SESSION['error_msg'] = '登录可以访问更多数据哦~';
            $this->redirectExit('/user/login');
        }
        // 当前用户信息.
        $this->user_info = $user_obj->getOne(array('id' => $_SESSION['uid']));
        $this->tpl_engine->assign('user_info', $this->user_info);
    }

    /**
     * 成功时候数据返回.
     *
     * @param array  $data              需要返回的数据.
     * @param string $msg               消息.
     * @param bool   $unescaped_unicode 是否需要转义Unicode.
     * @param bool   $original          数据是否已经是原始的,如果是拿么直接输出,否则会调用@genReturnData.
     */
    public function displaySuccessJson($data = null, $msg = 'ok', $unescaped_unicode = true, $original = false)
    {
        if (!$original) {
            $data = $this->genReturnData($data, $msg);
        }
        $this->displayJson($data, $unescaped_unicode);
    }

    /**
     * 失败的时候数据返回.
     *
     * @param string $msg               错误消息.
     * @param int    $error_code        错误代码.
     * @param bool   $unescaped_unicode 是否转义Unicode.
     */
    public function displayErrorJson($msg = 'failed', $error_code = 1, $unescaped_unicode = true)
    {
        // 这里可以记录失败日志.
        $this->displayJson($this->genReturnData(null, $msg, $error_code), $unescaped_unicode);
    }

    /**
     * 生成返回信息数据.
     *
     * @param mixed  $data       数据.
     * @param string $msg        消息.
     * @param int    $error_code 错误码.
     *
     * @return array
     */
    private function genReturnData($data = null, $msg = 'ok', $error_code = 0)
    {
        return array(
            'error' => $error_code,
            'msg' => $msg,
            'data' => $data,
        );
    }

    public function page404()
    {
        parent::page404(); // TODO: Change the autogenerated stub
    }
}
