<?php
/**
 * Created by PhpStorm.
 * User: shellvon
 * Date: 16/4/14
 * Time: 下午5:13.
 */

namespace Controller;

use MicroMan\MicroController;
use Model;

class IndexController extends MicroController
{
    public function index()
    {
        echo 'Index';
    }

    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub

        if (!isset($_SESSION['uid']) && strcasecmp($this->action_name, 'login') !== 0) {
            $this->redirectExit('/index/login');
        }
    }

    /**
     * 登录页面.
     */
    public function login()
    {
        $data = Model\UserModel::getInstance()->find('shellvon', 'p4s5w0rd');
        print_r($data);
        $this->displayJson(array());
        // $this->displayTpl(array('username' => 'shell-von', 'title' => 'Hello world by MicroMan'), null);
    }
}
